setup mocha configuration
svillegasz/psl-workshop-api-testing-js pull request #1
Opened 2017-09-21 19:50 UTC by svillegasz

2017-09-21 20:06 UTC, aperdomob requested changes

2017-09-21 20:06 UTC, aperdomob commented on test/HelloWorld.test.js
> + });
Agregar un salto de linea (EOF)

2017-09-21 22:03 UTC, aperdomob approved these changes

2017-09-21 22:42 UTC, germandavid85 approved these changes

2017-09-21 22:46 UTC, aperdomob approved these changes

2017-09-22 01:07 UTC, luisbolanoss approved these changes
LGTM

2017-09-23 23:36 UTC, merged